export const lesson = {
  number: "7.3.4",
  title: "Resource Release",
  screens: [
    {
      id: "hook",
      tab: "The good host",
      type: "reveal",
      kicker: "Screen 1 — Hook",
      headline: "A good host doesn't kick everyone out the moment the meal ends.",
      lead: "Some guests stay to help clear the table, the borrowed chairs and dishes go back to the neighbors who lent them, and everyone gets a proper goodbye — not a quiet slip out the back door nobody notices until the house is suddenly empty.",
      heading: "A good host doesn't kick everyone out the moment the meal ends. Some guests stay to help clear the table, the borrowed chairs and dishes go back to the neighbors who lent them, and everyone gets a proper goodbye — not a quiet slip out the back door nobody notices until the house is suddenly empty.",
      cta: "Reveal the release plan",
      image: "dinner-party-release",
      reveal: {
        title: "Resource release works the same way",
        text: "Resource release works the same way. Release is planned at the beginning, not improvised at the end. The resource management plan — written back in planning — already answers the questions closure now asks: when each role is released, to whom, by what procedure, and with what handover. Closure simply executes that plan.",
        image: "dinner-party-release",
      },
    },
    {
      id: "people",
      tab: "Releasing people",
      type: "accordion",
      kicker: "Screen 2 — Three Rules of Releasing People",
      headline: "Three Rules of Releasing People",
      heading: "The execution discipline for releasing people has three rules.",
      intro: "The execution discipline for releasing people has three rules. Click each to explore.",
      image: "three-release-rules",
      items: [
        { title: "Staged Release", text: "Staged Release follows the remaining work, not detonated on the last day. Closure itself needs hands — the contract file, the reconciliation, the archive, the transition sessions — and a project that releases everyone the moment the product ships discovers it has no one left to close with. Each person's release date follows their last closure obligation." },
        { title: "Formal", text: "A written release to the resource owner — the functional manager in a matrix organization, the resource pool, the staffing function — with the date, the performance input, and the handover status. The receiving side can plan, and the person's next chapter starts cleanly rather than by drift." },
        { title: "Individually Humane", text: "Feedback, recognition, and transition support are part of the release, not separate niceties." },
      ],
      after: { label: "The failure mode", text: "Evaporation — people peeling away informally as their tasks finish, until one day the project is simply unstaffed. No feedback was ever given, no formal release was ever recorded, access was never revoked, and nobody was ever thanked. Evaporation feels frictionless and costs the organization exactly the three things closure exists to protect: the records, the security, and the people's goodwill." },
    },
    {
      id: "resources",
      tab: "Non-human resources",
      type: "accordion",
      kicker: "Screen 3 — Non-Human Resources: Returned, Redeployed, or Retired",
      headline: "Returned, Redeployed, or Retired",
      heading: "Everything physical and digital the project borrowed or bought needs the same deliberate disposition. Click each to explore.",
      intro: "",
      image: "non-human-resources",
      items: [
        { title: "Equipment", text: "Devices, test rigs, specialized hardware — returned to its pool, transferred to operations with the product, or retired per asset policy. Test environments are released back to the shared infrastructure." },
        { title: "Facilities", text: "The team room, the workspace, the leased space — released per their terms. Leases and rentals are ended on their notice clauses, not allowed to auto-renew into orphaned costs." },
        { title: "Software Licenses", text: "Reassigned to their next users or cancelled — per-seat licenses billing against a finished project are the digital version of the open charge code." },
        { title: "Access Revoked", text: "Credentials, system accounts, repository permissions, badges, VPN profiles, third-party portal logins — terminated on each person's release date as a security obligation, not an IT afterthought. Orphaned accounts belonging to departed project members are a textbook attack surface and a standing audit finding." },
        { title: "Shared Artifacts", text: "Drives, repositories, boards — not deleted, but archived and handed to their permanent owners, completing the records obligation." },
      ],
    },
    {
      id: "adjourning",
      tab: "Adjourning",
      type: "reveal",
      kicker: "Screen 4 — Adjourning: The Team Ends by Design",
      headline: "The Team Ends by Design",
      heading: "Tuckman's model has five stages, and the exam expects the fifth one — the stage most teams skip entirely.",
      cta: "Reveal the fifth stage",
      image: "adjourning-arc",
      reveal: {
        title: "Adjourning: The Team Ends by Design",
        text: "Forming, storming, norming, performing — and adjourning: the deliberate disbanding of a team whose purpose is complete. Adjourning is a real stage with real dynamics: even on a successful project, endings carry loss — of rhythm, of identity, of the small culture a performing team built — and people process that loss better when the ending is marked than when it's denied. Handled well, adjourning consolidates everything the team became: the closure rituals tell the story to completion; the feedback crystallizes what each person grew into; the formal releases give everyone a clean edge between this chapter and the next; and the relationships survive as the informal network — the community-of-practice tissue — that future projects will quietly run on. Handled badly, adjourning teaches the organization's best people a corrosive lesson: that endings don't matter, that performance dissolves into silence, and that the next project's kickoff enthusiasm is a loan that will never be repaid. Project managers who close teams well are, measurably, the ones whose next teams form fastest.",
        image: "adjourning-arc",
      },
    },
    {
      id: "exam",
      tab: "Exam lens",
      type: "reveal",
      kicker: "Screen 5 — Synthesis (Exam Lens)",
      headline: "The goodbyes at the door were never a formality.",
      heading: "Back to that dinner party one more time — because the goodbyes at the door were never a formality. They were what made everyone actually want to come back next time.",
      cta: "Reveal the exam lens",
      image: "exam-dinner-party",
      reveal: {
        title: "Synthesis (Exam Lens)",
        text: "Release is planned at the beginning, executed at closure: staged with the remaining work, formal through a written release to the resource owner, and individually humane through feedback, recognition, and transition support — never left to evaporate. Non-human resources get the same deliberate disposition: equipment returned or retired, facilities released on their notice clauses, licenses reassigned or cancelled, access revoked as a security obligation, and shared artifacts archived rather than deleted. And the team itself ends by design — adjourning, Tuckman's fifth stage — consolidating what the team became rather than letting it dissolve into silence.",
        bullets: [
          "Three rules for releasing people: staged (tied to remaining closure obligations), formal (written release to the resource owner), individually humane (feedback, recognition, transition support)",
          "Evaporation — informal, undocumented departure — costs records, security, and goodwill all at once",
          "Non-human resources: equipment returned/retired, facilities released on notice, licenses reassigned/cancelled, access revoked (security obligation), shared artifacts archived not deleted",
          "Tuckman's fifth stage, adjourning, is expected on the exam — handled well, it consolidates the team's story; handled badly, it teaches people that endings don't matter",
        ],
        image: "exam-dinner-party",
      },
    },
  ],
};
